name: PenguinAuctionHouse
main: com.penguinmc.auction.PenguinAuctionHouse
version: 1.0.0
api-version: 1.21
author: PenguinMC
commands:
  ah:
    description: Open the auction house GUI
    usage: /ah
  ah sell:
    description: Sell an item to the auction house
    usage: /ah sell <amount> <material>
